create table PAGE_ENTITY (
    id integer not null primary key,
    per_page integer not null,
    total_movies integer not null,
    total_pages integer not null
);

create table MOVIE_ENTITY (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title varchar,
    year_num varchar,
    rated varchar,
    released varchar,
    runtime varchar,
    genre varchar,
    director varchar,
    writer varchar,
    actors varchar,
    page_id integer not null references PAGE_ENTITY(id)
);
create index MOVIE_IDX_DIR on MOVIE_ENTITY(director);
